name: wunderlust
favicon: null
layout_spectrum: 0.5472121303901076
typography_spectrum: 0.21312980516813695
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0702'
    - '#fffffd'
    - '#313e4e'
    - '#bc8f50'
    - '#f6cb8e'
  brandStrength: 0.6952645312994719
  lightness: 0.4425475257448852
  saturation: 0.10455010994337499
  rhythmicContrast: 0.9412531480193138
purpose: []
