name: wunderlust
favicon: null
layout_spectrum: 0.5472121303901076
typography_spectrum: 0.21312980516813695
title: wunderlust
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#221e1f'
    - '#fca86a'
    - '#746457'
    - '#8aa5c6'
    - '#d9d0cb'
  brandStrength: 0.6952645312994719
  lightness: 0.4425475257448852
  saturation: 0.5
  rhythmicContrast: 0.25
purpose: []
